<?php
/**
 * !! DO NOT EDIT THIS FILE, EDIT config.inc.php INSTEAD !!
 * 
 * Default configuration file for the Mikeotizels M-PESA API SDK PHP package.
 * 
 * This file contains default settings for all available configuration options
 * for this package. You can copy configuration options from here to your local
 * configuration file config.inc.php and fill in your custom values.
 * 
 * Note that some options can be overridden at runtime. For, example, if you 
 * want to use the SDK with multiple accounts, you can save the settings in
 * your database and pass the options dynamically when initializing the Mpesa 
 * object or when making a specific API request.
 * 
 * @package    Mikeotizels/Mpesa
 * @subpackage Configuration
 * @author     Michael Otieno <mikeotizels@gmail.com>
 * @copyright  Copyright 2022-2024 Michael Otieno
 * @license    Licensed under The MIT License (MIT). For the license terms, 
 *             please see the LICENSE file that was distributed with this 
 *             source code or visit <https://opensource.org/licenses/MIT>.
 * @since      2.0.0
 */

return [

    /**
     * Environment Type
     * 
     * Specifies the current working environment, which influences various
     * functionalities for this package, including things like error handling.
     * 
     * This can be set to either 'sandbox' or 'live'. When set to sandbox, the 
     * isolated testing environment is used. When set to live, the production
     * domain is used. If not specified, it defaults to 'sandbox'.
     * 
     * Setting the environment as 'sandbox' also means it pretty much reports 
     * every problem that might occur. However, errors are never displayed in
     * production environment, instead they are generally saved to the error
     * log for monitoring and debugging.
     * 
     * @since 2.0.0
     *
     * @var string
     */
    'environment' => 'sandbox',

    /**
     * Account Details
     * 
     * Sets up the M-PESA account details to be used to send API requests.
     *  
     * @since 2.0.0
     * 
     * @var array<string, integer|string>
     */
    'account' => [
        'merchant_name'      => '',
        'short_code'         => '',
        'initiator_name'     => '',
        'initiator_password' => ''
     ],

    /**
     * App Credentials
     * 
     * Sets up the M-PESA application credentials to be used to to obtain the 
     * OAuth Access Token.
     * 
     * @since 2.0.0
     *
     * @var array<string, string>
     */
    'app' => [
        'consumer_key'    => '',
        'consumer_secret' => ''
    ], 

    /**
     * API Endpoints
     * 
     * These are the endpoints for the M-PESA APIs supported by this package.
     * 
     * These should be relative URLs, they will be merged with the base URL 
     * depending on the current environment type to form a complete URL.
     * 
     * @since 2.0.0
     * 
     * @var array<string, string>
     */
    'endpoints' => [
        'oauth'             => 'oauth/v1/generate?grant_type=client_credentials',
        'stkpush'           => 'mpesa/stkpush/v1/processrequest',
        'stkpushquery'      => 'mpesa/stkpushquery/v1/query',
        'c2bregisterurl'    => 'mpesa/c2b/v1/registerurl',
        #'c2bsimulate'       => 'mpesa/c2b/v1/simulate', // @deprecated 2.0.0
        'b2c'               => 'mpesa/b2c/v3/paymentrequest',
        'b2b'               => 'mpesa/b2b/v1/paymentrequest',
        'transactionstatus' => 'mpesa/transactionstatus/v1/query',
        'accountbalance'    => 'mpesa/accountbalance/v1/query',
        'reversal'          => 'mpesa/reversal/v1/request',
        'qrcode'            => 'mpesa/qrcode/v1/generate'
    ], 

    /**************************************************************************
     * APIs Configuration
     * 
     * This section contains settings for the default request parameter values 
     * to be used with each API endpoint. You can refer to each API's docs for
     * detailed information about a specific configuration option.
     */

    /**
     *-------------------------------------------------------------------------
     * Dynamic QR Code API (Production Only)
     *-------------------------------------------------------------------------
     *
     * This section contains the default settings for some request parameters
     * required by the M-PESA Dynamic QR Code API endpoint.
     * 
     * @see https://developer.safaricom.co.ke/APIs/DynamicQRCode
     *
     * @since 2.0.0
     *
     * @var array<string, integer|string>
    */
    'qrcode' => [
        'trxcode' => 'PB', 
        'size'    => 300
    ],

    /**
     *-------------------------------------------------------------------------
     * STK Push (M-Pesa Express/Lipa na M-PESA Online) API
     *-------------------------------------------------------------------------
     *
     * This section contains the default settings for some request parameters
     * required by the M-PESA STK Push API endpoints.
     *
     * @see https://developer.safaricom.co.ke/APIs/MpesaExpressSimulate
     * @see https://developer.safaricom.co.ke/APIs/MpesaExpressQuery
     *
     * @since 2.0.0
     *
     * @var array<string, string|null>
    */
    'stkpush' => [
        'passkey'          => '',
        'transaction_type' => 'CustomerPayBillOnline',
        'callback_url'     => ''
    ],

    /**
     *-------------------------------------------------------------------------
     * Customer To Business (C2B) API
     *-------------------------------------------------------------------------
     *
     * This section contains the default settings for some request parameters
     * required by the M-PESA C2B API endpoints.
     * 
     * @see https://developer.safaricom.co.ke/APIs/CustomerToBusinessRegisterURL
     *
     * @since 2.0.0
     *
     * @var array<string, string|null>
    */
    'c2b' => [
        'command_id'       => 'CustomerPayBillOnline',
        'response_type'    => 'Completed',
        'confirmation_url' => '',
        'validation_url'   => ''
    ],

    /**
     *-------------------------------------------------------------------------
     * Business To Customer (B2C) API
     *-------------------------------------------------------------------------
     *
     * This section contains the default settings for some request parameters
     * required by the M-PESA B2C API endpoint.
     * 
     * @see https://developer.safaricom.co.ke/APIs/BusinessToCustomer
     *
     * @since 2.0.0
     *
     * @var array<string, string|null>
    */
    'b2c' => [
        'command_id'         => 'BusinessPayment',
        'queue_time_out_url' => '',
        'result_url'         => ''
    ],

    /**
     *-------------------------------------------------------------------------
     * Business To Business (B2B) API
     *-------------------------------------------------------------------------
     *
     * This section contains the default settings for some request parameters
     * required by the M-PESA B2B API endpoint.
     * 
     * @see https://developer.safaricom.co.ke/Documentation 
     *
     * @since 2.0.0
     *
     * @var array<string, integer|string|null>
    */
    'b2b' => [
        'command_id'             => 'BusinessPayBill',
        'sender_identifier_type' => 4,
        'queue_time_out_url'     => '',
        'result_url'             => ''
    ],

    /**
     *-------------------------------------------------------------------------
     * Transaction Status API
     *-------------------------------------------------------------------------
     *
     * This section contains the default settings for some request parameters
     * required by the M-PESA Transaction Status API endpoint.
     * 
     * @see https://developer.safaricom.co.ke/APIs/TransactionStatus
     *
     * @since 2.0.0
     *
     * @var array<string, integer|string|null>
    */
    'transactionstatus' => [
        'command_id'         => 'TransactionStatusQuery',
        'identifier_type'    => 4,
        'queue_time_out_url' => '',
        'result_url'         => ''
    ],

    /**
     *-------------------------------------------------------------------------
     * Account Balance API
     *-------------------------------------------------------------------------
     *
     * This section contains the default settings for some request parameters
     * required by the M-PESA Account Balance API endpoint.
     * 
     * @see https://developer.safaricom.co.ke/APIs/AccountBalance
     *
     * @since 2.0.0
     *
     * @var array<string, integer|string|null>
    */
    'accountbalance' => [
        'command_id'         => 'AccountBalance',
        'identifier_type'    => 4,
        'queue_time_out_url' => '',
        'result_url'         => ''
    ],

    /**
     *-------------------------------------------------------------------------
     * Reversal API
     *-------------------------------------------------------------------------
     *
     * This section contains the default settings for some request parameters
     * required by the M-PESA Reversal API endpoint.
     * 
     * @see https://developer.safaricom.co.ke/APIs/Reversal
     *
     * @since 2.0.0
     *
     * @var array<string, integer|string|null>
    */
    'reversal' => [
        'command_id'               => 'TransactionReversal',
        'reciever_identifier_type' => '',
        'queue_time_out_url'       => '',
        'result_url'               => ''
    ],

    /**************************************************************************
     * Misc. Configuration
     * 
     * This section contains the "miscellaneous" settings for this package.
     * You may override these in your local config.inc.php file, but chances 
     * are that you may not need to.
     */

    /**
     * Cert Config
     * 
     * - Cert File
     * 
     * The location of an M-PESA Security Certificate file (a X509 certificate)
     * on the local filesystem, which contains a public security key to be used 
     * when generating the Security Credential for authenticating a transaction.
     * 
     * - Cert Path
     * 
     * The path to the directory where the M-PESA certificate files are stored. 
     * The specified directory path needs to be readable by the web server.
     * 
     * If cert.file is not specified or if the specified file is not found, the
     * directory pointed to by cert.path is searched for a suitable certificate
     * depending on the current environment type. For example, when in testing
     * environment, the "mpesa_sandbox.cer" file is used. In live environment, 
     * the "mpesa_production.cer" file is used by default. 
     * 
     * Leave blank for the default location ('<base_dir>/certs').
     * 
     * @since 2.0.0
     *  
     * @var array<string, string>
     */
    'cert' => [
        'file' => '',
        'path' => '',
    ],

    /** 
     * Cache Config
     * 
     * - Cache Enable
     * 
     * Turns on or off caching.
     * 
     * Please note that the Cache class for this package currently only supports 
     * the native filesystem cache storage which might be performance sensitive 
     * to read and write. Use the caching functionality with care, and remember 
     * to benchmark your application, as a point may come where disk I/O will 
     * negate positive gains by caching. 
     * 
     * - Cache Path
     * 
     * The path to the directory where temporary cache files should be stored. 
     * For security reasons, the specified directory should be writable and 
     * readable by the web server, but not accessible via a web browser. 
     * 
     * Leave blank for the default location ('<base_dir>/cache').
     * 
     * @since 2.0.0
     * 
     * @var array<string, boolean|string>
     */
    'cache' => [
        'enable' => true,
        'path'   => '',
    ],

    /** 
     * Log Config
     * 
     * - Log Enable
     * 
     * Whether enable logging for monitoring and debugging.
     * 
     * - Log Path
     * 
     * The path to the directory where log files should be stored. 
     * For security reasons, the specified directory should be writable and 
     * readable by the web server, but not accessible via a web browser. 
     * 
     * Leave blank for the default location ('<base_dir>/logs').
     * 
     * @since 2.0.0
     *   
     * @var array<string, boolean|string>
     */
    'log' => [
        'enable' => true,
        'path'   => '',
    ]
];